# Generated by Django 2.2 on 2025-04-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_false',
            new_name='is_staff',
        ),
    ]
